### ISSUE TITLE
Tako is deprecated and should be deleted

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/tako#160]
Tako has been replaced by Biz Ops as the single source of truth for repositories.

**Comment by JakeChampion** [comment]
Rather than delete, perhaps it would be better to update the readme to
state biz ops is the tool to use and then to archive the GitHub repository

**Comment by adambraimbridge** [comment]
Todo: 
 - [ ] update the readme to state biz ops is the tool to use 
 - [ ] archive the GitHub repository
