### ISSUE TITLE
Using Biz Ops as a data source

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/tako#27]
1. We can define ownership of next repositories as *the list of repos that `next-tako` manages*

2. We could also define ownership of next repositories as *the list of next repositories from Biz Ops* 
     - [See this Dewey link](https://dewey.in.ft.com/search/home?basicSearch=next&f_type.raw_4=repository)

~We should explain why 1 is better than 2.~

**Comment by adambraimbridge** [comment]
Related: https://github.com/Financial-Times/next/issues/193#issuecomment-427427561

**Comment by lucas42** [comment]
Who says that biz-ops is meant to be un-opinionated?  The data layer is flexible so you should be able to shove as many opinions into it as you want.
We don't want to put next-specific business logic into the biz-ops view layer, but there's nothing stopping you from using its data layer as your canonical data source and annotating it with your own custom details.

**Comment by sjparkinson** [comment]
> We don't want to put next-specific business logic into the biz-ops view layer, but there's nothing stopping you from using its data layer as your canonical data source and annotating it with your own custom details.

Okie dokie, the question then is how do we do that? Specific requirement would be to surface the topics of a repository via the API.

I think our rough plan is going to be to continue with this, because then we can agree on a shared schema for our tools, but where this gets its data from can/should change in future.

/cc @lucas42 @wheresrhys

**Comment by lucas42** [comment]
Here's a rough stab at getting topics: https://github.com/Financial-Times/github-importer/pull/10

**Comment by sjparkinson** [comment]
We had a IRL meeting about this, see https://financialtimes.slack.com/archives/CD689QU2K/p1541499781012800.
