### ISSUE TITLE
API returns 404 when starting

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/tako#37]
We start with...

```js
probot.load(setupApp)
probot.start()
```

from [`probot-run.js`](https://github.com/probot/probot/blob/7831ef0c4dacd30ce91a6db60ec63aa4c7a0f071/bin/probot-run.js#L37-L38). `load()` is defined as...

```js
public load (appFn: string | ApplicationFunction) {
  if (typeof appFn === 'string') {
    appFn = resolve(appFn) as ApplicationFunction
  }

  const app = new Application({ app: this.app, cache, githubToken: this.githubToken })

  // Connect the router from the app to the server
  this.server.use(app.router)

  // Initialize the ApplicationFunction
  app.load(appFn)
  this.apps.push(app)

  return app
}
```

in [`index.ts`](https://github.com/probot/probot/blob/7831ef0c4dacd30ce91a6db60ec63aa4c7a0f071/src/index.ts#L80-L94).

Which basically calls our `index.js`...

https://github.com/Financial-Times/tako/blob/5716169e8ab9acf391794bc78df81d9c783587f3/src/index.js#L8

And what we see from all of this is that express is started and listening for a period of time before we have finished the `initialise(app)` and `routes(app)` calls in `index.js`.

So that if you ask for `/tako/repositories` before then, you get a 404!

Is there anything we could do to block express from starting, until we have initialised and loaded our routes?

**Comment by sjparkinson** [comment]
Rough timeline, ~5 seconds for the app to initialise and routes to register with express.

```
14:44:08.060Z  INFO probot: Forwarding https://smee.io/4RokodNXBYMvVv to http://localhost:3000/
14:44:08.066Z  INFO probot: Listening on http://localhost:3000
14:44:08.417Z  INFO probot: Connected https://smee.io/4RokodNXBYMvVv
14:44:13.102Z  INFO init: Loaded 235 repositories
14:44:13.104Z  INFO api: Registered the /tako router
```

**Comment by adambraimbridge** [comment]
@sjparkinson Is this issue now resolved?

**Comment by sjparkinson** [comment]
Yeah still an issue, but I think it's not something we can easily address. It doesn't affect too much really so this issue is more of a heads up.
