### ISSUE TITLE
Archived repositories

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/tako#46]
What do we do about archived repositories that might have Tako installed?

1. Continue as we are

2. Continue as we are, but surface the archived property

3. Change Tako to not store/track archived repositories

Personally I'm leaning towards option 3, which would be great for someone else to work on.

**Comment by sjparkinson** [comment]
Thanks @quarterto for bringing this to my attention!

**Comment by adambraimbridge** [comment]
See https://github.com/Financial-Times/tako/pull/67
