### ISSUE TITLE
Express returns a 404 on errors

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/tako#75]
If there's an error while handling a request, express seems to respond with a 404.

The error is logged correctly, so no problem there.

https://expressjs.com/en/guide/error-handling.html

**Comment by adambraimbridge** [comment]
The probot Express application returns a 404 ...
![image](https://user-images.githubusercontent.com/224547/51532427-fbea9480-1e37-11e9-8e9a-90fa5072f896.png)

... and throws the error in the server logs
![image](https://user-images.githubusercontent.com/224547/51532410-f2612c80-1e37-11e9-85de-c555bf97f557.png)

(Possibly) Related links 
- https://github.com/probot/probot/blob/master/src/middleware/log-request-errors.ts
- https://github.com/probot/probot/blob/master/src/server.ts#L7
- https://github.com/probot/probot/blob/master/src/index.ts#L64

**Comment by adambraimbridge** [comment]
I'd say this is either `Blocked` on further investigation into Probot's approach to error handling, or `Won't Fix` or both :)

**Comment by sjparkinson** [comment]
Yeah, won't fix for us. Should be resolved upstream.

I'll raise this as an issue on https://github.com/probot/probot now that it's active again.

**Comment by gr2m** [comment]
Probot was inactive? :) 

Could you see if you can investigate the bug on Probot? I'm focusing on the Probot v8 right now and the other maintainers are pretty busy right now. But happy to help review pull requests or help out with questions

Love that FT is using Probot! 🤖❤️

**Comment by adambraimbridge** [comment]
This can't be fixed here.
