### ISSUE TITLE
Only the first 100 repositories have topics

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/tako#79]
The response from https://tako.in.ft.com/tako/repositories now includes GitHub topics for each repository.

However, after the first hundred repositories, the topics are missing. 

![image](https://user-images.githubusercontent.com/224547/51106518-ea740d80-17e3-11e9-9153-b0a1f38d8201.png)

The cause is most certainly this: https://github.com/probot/probot/issues/760

**Comment by adambraimbridge** [comment]
From @sjparkinson:

> Sounds like we should move to using the .paginate method that is bundled with octokit then, rather than the current one in Probot, when #744 is released. If that's possible. Yes it is, from the PRs description 👍 .

**Comment by ker-an** [comment]
Note for Keran: The new version of Probot comes with a new method called paginate but same name as old function called paginate (look out for two paginates)

**Comment by ker-an** [comment]
Resolved via #101
