### ISSUE TITLE
Handle appropriate "archived" events

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/tako#80]
See: https://github.com/Financial-Times/tako/pull/68#pullrequestreview-191316376

**The problem**
If you archive a Tako repository, the repository is not removed from the /tako/repositories list. Likewise, unarchiving doesn't add it.

**The solution** 
Notify Tako whenever a repository is archived, unarchived or deleted. There's a GitHub webhook for this: https://developer.github.com/v3/activity/events/types/#repositoryevent

**Tasks**
- [x] Configure Probot to listen to the `repositoryevent` GitHub webhook

Not sure how to do this, but it should either become part of the Tako installation process, or Tako's README should have sufficient instructions.

**Comment by sjparkinson** [comment]
Resolved in https://github.com/Financial-Times/tako/pull/84.
