### ISSUE TITLE
Add Secret Squirrel

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/tako#9]

**Comment by adambraimbridge** [comment]
Should I add SS manually, or should I use `tako` to add Secret Squirrel to itself?

**Comment by simonplend** [comment]
Good questions!

I reckon for now, in the interest of avoiding us accidentally committing secrets to tako, it's best to just add it manually. I think that creating an app for automatically opening a PR that adds Secret Squirrel to a repo would be excellent :ok_hand: It could be an app that tako installs on repos that it manages.

As for tako managing itself, that's a tricky one... :thinking:

**Comment by adambraimbridge** [comment]
I think `tako` _should_ be responsible for its own repository. We want it to have the same security and dependency management as any other repository.

So I vote to use `tako` to add Secret Squirrel to itself.

That means I need to know how to find out which repositories `tako` "owns"

**Comment by simonplend** [comment]
On it: https://github.com/financial-times-sandbox/tako/issues/10

**Comment by adambraimbridge** [comment]
> creating an app for automatically opening a PR that adds Secret Squirrel to a repo would be excellent 👌 It could be an app that tako installs on repos that it manages.

That's a good idea. 

I guess it doesn't have to be a blocker

I'll add ss manually and figure out the self-awareness thing later
